### ISSUE TITLE
issue with code - not printing fifth 

### ISSUE THREAD

**Issue by Mukango18** [modularizer/pyprez#4]
**Exercise 5: Conversion**
Convert the tuple, "Third" to an array.
Double all the elements in "Third"
Add the elements in this array to the elements in "Fourth".
To do this, use only 1 arithmetic statement. Store this result as "Fifth" and print it.

Hint Answer should look like this.
Fifth = 2*___(____) + _____
print (Fifth)

**CODE**:
``import numpy as np

third = (-6,-18,-10,-4,-90,-55,-56)
fourth =[6],[18],[10],[4],[90],[55],[56]
fourth = np.array(fourth)
print(third)
print(type(third))
print("After converting Python tuple to array")

arr = np.asarray(third)
print(arr)
print(type(arr))

print(f"{arr.shape=}, {fourth.shape=}, {fourth.flatten().shape=}, {fourth[:,0].shape=}")

fifth = 2*arr + fourth[:,0]
print(f"{fifth=}")

print(fifth)`

**OUTPUT:** 
(-6, -18, -10, -4, -90, -55, -56)
<class 'tuple'>
After converting Python tuple to array
[ -6 -18 -10  -4 -90 -55 -56]
<class 'numpy.ndarray'>
arr.shape=(7,), fourth.shape=(7, 1), fourth.flatten().shape=(7,), fourth[:,0].shape=(7,)
fifth=array([ -6, -18, -10,  -4, -90, -55, -56])
[ -6 -18 -10  -4 -90 -55 -56]

**Comment by modularizer** [comment]
I'm not quite understanding the issue that you are facing. The output text you posted above seems like what I would expect.

If you are having trouble with the runnable code snippet can you attach a screenshot of what the output looks like for you? It looks like this for me on Chrome on Windows. 
![image](https://user-images.githubusercontent.com/82345008/197121170-3b1acf22-087d-4940-acdc-83db2290f7a7.png)
Also, which browser and operating system are you using? Thanks.

just for reference, the original post is [here](https://stackoverflow.com/questions/74148106/conversion-beginner/74148218#comment130914596_74148218)
