### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by abolinsky** [modularizer/pyprez#9]
Would you consider including a license to make the copyright claims explicit?

**Comment by modularizer** [comment]
I just added the "unlicense" LICENSE file, meaning you are free to do whatever you want with the code as long as you don't hold me liable. Hope this works for you! I would of course appreciate it if you give me credit, but I will not require or enforce it. I'm curious what you are working on as well. Shoot me an email if you want to tell me about it or need help. Thanks!
